### ISSUE TITLE
DocsLogo component causes page fail for non-ember starting addon names

### ISSUE THREAD

**Issue by bravo-kernel** [ember-learn/ember-cli-addon-docs#111]
Any idea what could be causing this? Fresh addon with most basic Addon Docs, have not added the component in any of my pages.

> Assertion Failed: You passed "undefined" to the docs-logo component, but the only valid options are [ember,ember-cli,ember-data]."

**Comment by samselikoff** [comment]
Believe the hero or some other component is using it and needs a ‘logo’ prop

**Comment by samselikoff** [comment]
Should make this clear from the caller

**Comment by bravo-kernel** [comment]
I just installed `ember-cli-htmlbars` as a dependency (after comparing with my working add-on) and that seems to solve the problem.

Let me retry if I can reproduce again, my steps were:

1. `ember addon my-test-addon`
2. then straight through with ember-cli-addon-docs

**Comment by bravo-kernel** [comment]
Unfortunately I can only reproduce the error (about 100 times now), the fix was a false positive.

Could be some f** up on my behalf since I have a working addon with similar file/folder structure. I will give it another go tomorrow.

**Comment by bravo-kernel** [comment]
Found the cause.

It seems `name` in `index.js` is used to determine which Ember logo to display. Changing the name to e.g. `my-test-addon` (as I did) will cause described error. Perhaps a different check or error message could save other people some hurt.

```js
// index.js
'use strict';

module.exports = {
  name: 'ember-test-addon'
};
```

**Comment by bravo-kernel** [comment]
Makes me wonder.. should we not be able to use Addon Docs for all addons? I can imagine documenting an engine addon with a name not starting with `ember` etc.

**Comment by Dhaulagiri** [comment]
I noticed this happens because the regex [here](https://github.com/ember-learn/ember-cli-addon-docs/blob/ffdb902c19c9bec9046e208d8abe8d180903d817/addon/components/docs-viewer/x-nav/component.js#L20-L29) assumes your addon starts with the word `ember`.  I relaxed this a bit in https://github.com/ember-learn/ember-cli-addon-docs/pull/117 to support scoped packages which _should_ make this better but it doesn't seem to entirely fix the problem that the addon has to have the word `ember` in it somewhere.

**Comment by bravo-kernel** [comment]
👏
