### ISSUE TITLE
Allow ability to configure branch name

### ISSUE THREAD

**Issue by tim-evans** [ember-learn/ember-cli-addon-docs#181]
Currently, the [`{{x-main}}`](https://github.com/ember-learn/ember-cli-addon-docs/blob/master/addon/components/docs-viewer/x-main/component.js#L79-L86) component in the `{{docs-viewer}}` has hard-coded URLs that assume that the main branch of the repo is always `master`. I use `latest` for my repositories, and would like the "Edit docs" link to work 😅 

Any guidance as to the best way to achieve this is welcome, as I'd be up to making a PR for this particular issue.

**Comment by tim-evans** [comment]
`master` within the context of how it’s used in git is inherently racist. Don’t @ me 😂

**Comment by dfreeman** [comment]
I remember seeing that blog post or whatever it was go around a while back as well—though literally any name other than `latest` would be easier for us to accommodate, just because that happens to be the term we landed on for describing the most recent published release 😜 (Maybe we should use something like "stable" instead?)

I think this is something we should bear in mind as we look at landing #188/#164 — taking `latest` out of the URL helps, but I think we're still using that identifier internally as things stand in those PRs right now. Since we're going to be breaking `versions.json` anyway, now would be the time to make this sort of change as well.

**Comment by tim-evans** [comment]
That sounds great, thanks for hearing me out on this. 😄 

Y'all are doing fantastic work here- it's amazing how easy it is to setup my addons to have docs!

**Comment by RobbieTheWagner** [comment]
This is configurable now, though `latest` specifically might cause problems.
