### ISSUE TITLE
Importing HBS compiler messes up sourcemaps

### ISSUE THREAD

**Issue by pzuraq** [ember-learn/ember-cli-addon-docs#182]
I've been having sourcemaps be messed up in various projects and finally tracked it down to this import. Unsure why it's causing the issue, but it definitely is.

https://github.com/ember-learn/ember-cli-addon-docs/blob/master/index.js#L102

With import

![screen shot 2018-05-16 at 3 26 04 pm](https://user-images.githubusercontent.com/685518/40147242-c8899940-591d-11e8-8ef0-6eb9f5e2d4b7.png)

Without import

![screen shot 2018-05-16 at 3 25 24 pm](https://user-images.githubusercontent.com/685518/40147243-c8d27c8c-591d-11e8-90d1-2b9e5ff3feef.png)

**Comment by dfreeman** [comment]
It looks like the sourcemap for the template compiler includes info for a bunch of files of the same name as those in Ember's own sourcemap (including `ember-metal.js` in your screenshot above).

We could filter that sourcemap out so that it doesn't get picked up when concatenating together imported files, though that would result in a warning like this in every build:

```
Warning: ignoring input sourcemap for vendor/ember-source/ember-template-compiler.js because ENOENT: no such file or directory, open '/Users/dfreeman/code/ember-cli-addon-docs/tmp/source_map_concat-input_base_path-yqVgTR7i.tmp/vendor/ember-source/ember-template-compiler.map'
```

I honestly wonder a little bit about the utility of the live example feature. It's really cool in theory, but in practice it's only workable for component-only addons. Granted, there are plenty of those, but I wonder if a more structured [kitchen sink-style demo](https://ace.c9.io/build/kitchen-sink.html) might be better for that use case than an editable template anyway?

**Comment by pzuraq** [comment]
We could combine it with the Cookbook idea proposed in #168, and leverage Twiddle or something like it to give users a full playground to play around i

**Comment by dfreeman** [comment]
Does it make sense for us to drop the live-example stuff here and let ember-twiddle be the single community solution for live code editing? Then folks interested in setting up a playground like that could focus on adding support in ember-twiddle for easy embedding, from addon-docs or otherwise.

At present it looks like our own dummy app [is the only thing using `live-example`](https://emberobserver.com/code-search?codeQuery=live-example) 🙂 

@samselikoff what do you think?

**Comment by samselikoff** [comment]
Sure we can remove :) 

I can always add it in Mirage's dummy app (for example) if I want it. Nice to have it git history here in case I want to grab the behavior.

Go for it! 🔥
