### ISSUE TITLE
Documenting an action with DDAU in mind

### ISSUE THREAD

**Issue by dcyriller** [ember-learn/ember-cli-addon-docs#219]
Hello contributors of this nice addon 👋 

I'm wondering how I could document a component's function / method.

Specifically, I have an addon that exposes a component:
```hbs
{{my-component number=theNumber update=(action 'handleNumberUpdate'}}
```
The component implements data-down-action-up pattern.

How could I document the `update` function 🤔?

I find YUIdoc's method very convenient
```js
/**
  A description here

  @method update
  @param {string} number The number
  @param {Object} metadata The number metadata
  @param {string} metadata.value The first value in metadata
*/
update() {}
```
as I get this:
![capture d ecran 2018-08-16 a 15 16 05](https://user-images.githubusercontent.com/6677373/44211007-3739b680-a168-11e8-8e04-30cc365b5173.png)

But it's flagged a `internal` at the doc generation. 
![capture d ecran 2018-08-16 a 15 24 51](https://user-images.githubusercontent.com/6677373/44211123-913a7c00-a168-11e8-871b-1a2d309e493b.png)

And semantically, `@argument` would make more sense. But when using `@argument`, I loose the nice detail generation. I get this: 
![capture d ecran 2018-08-16 a 15 20 48](https://user-images.githubusercontent.com/6677373/44210972-26894080-a168-11e8-8e2a-e7e60592ed1a.png)

Has anyone an idea on this?

**Comment by pzuraq** [comment]
Generally, we don't model actions as _methods_, but as _arguments_ which are functions. It's more like your component is being passed a callback which it can call, rather than having a method overridden. If we ever do move towards something like Glimmer components' `this.args` hash this will make more sense, because you would have to access `this.args.update` to get that function.

In the meantime, I recommend that you don't define a default function, and instead replace it with `null` so it's less confusing and more clear that this is meant to be something passed in.

```js
export default class FooComponent extends Component {
  action = null;
}

export default Component.extend({
  action: null,
});
```

This is especially important for perf in native classes due to _shaping_, where an instance's hidden class is defined. Essentially, if you're going to have a value that is assigned on each instance, it should _always_ be assigned as a class field (or in the constructor) so that the instances result in the same hidden class ([more on that here](https://medium.com/faster-javascript/hidden-classes-in-javascript-and-inline-caching-6bc2a318c4b4)).

Even if you decide to continue defining a default function, you should document the action as an argument. Check out the [sandbox examples](https://ember-learn.github.io/ember-cli-addon-docs/sandbox/api/components/yuidoc-component#onEvent) for how we do that.

**Comment by dcyriller** [comment]
Thank you for your indepth answer @pzuraq. It's good to know this.

I'll use `@argument` and default `update` to `null` as you suggested. It's good to know the reason why! :)

Closing the issue then.
