### ISSUE TITLE
Design versioned API docs feature

### ISSUE THREAD

**Issue by samselikoff** [ember-learn/ember-cli-addon-docs#3]

**Comment by sivakumar-kailasam** [comment]
Things to do to get a single version doc viewer to work:
- Generate the YUIDoc structure from the target app/addon's code
- Modify [ember-learn/ember-jsonapi-docs](https://github.com/ember-learn/ember-jsonapi-docs) so that it can be added as a dependency to this addon to generate the models that this app can then use to render the views. 
- Link to appropriate external libs in the docs(Nice to have). eg., `MyAddonClass extends ThirdPartyClass`. So in this case we should be able to link to the github url for the ThirdPartyClass.

**Comment by samselikoff** [comment]
Follow along in https://github.com/ember-learn/ember-cli-addon-docs/pull/4
