### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by samselikoff** [ember-learn/ember-cli-addon-docs#30]
Wanted to start moving Mirage over to use this (and to help flesh out docs), ran into this:

![image](https://user-images.githubusercontent.com/2922250/31036644-35505c4a-a53b-11e7-99e6-d0000fad3dea.png)

**Comment by dfreeman** [comment]
Just tried installing addon-docs into Mirage — I didn't hit the `checker.assertAbove` exception (in the past when I've seen that it was when I had another addon linked?), but the marked/highlight.js thing is definitely an issue.

It looks like marked is interpreting the chunk with no leading `*`s in [this comment](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/model.js#L189-L229) as a single contiguous code block that it can't guess the language for. I just pushed a fix to let highlight.js just make a best guess when that happens (since blowing up is never good), but I'm guessing you'll wind up wanting to reformat that doc comment anyway.
