### ISSUE TITLE
Order of dependent addon "included" hooks

### ISSUE THREAD

**Issue by samselikoff** [ember-learn/ember-cli-addon-docs#319]
I'm working on improving the syntax highlighting, and I came across something interesting.

We set some options to be used by `ember-code-snippet` [here](https://github.com/ember-learn/ember-cli-addon-docs/blob/master/index.js#L110). Notice that this is _after_ we call

```js
this._super.included.apply(this, arguments);
```

I was trying to add the option `includer.options.includeHighlightStyle = false`, so `ember-code-snippet` wouldn't automatically include its default `highlight.js` styles, but when I tried, it wasn't taking effect.

I started debugging and found that `ember-code-snippet`'s `included()` hook was running before `ember-cli-addon-docs`'s was.

I added `ember-code-snippet` to `ember-cli-addon-docs`'s `"before"` key in our `package.json` to ensure it ran first, but still, my debugger hit inside of `ember-code-snippet`'s `included` hook first.

Only if I moved the options code to before the call to `this._super` was I able to get it working.

Could someone help explain this to me? What is the "right" way to set options like this? What code should go before the `this._super` call, and what code should go after? I've mostly seen other addons calling `this._super` at the top or nearly the top of their included hooks.

cc @dfreeman @pzuraq

**Comment by dfreeman** [comment]
> I added `ember-code-snippet` to `ember-cli-addon-docs`'s `"before"` key in our `package.json` to ensure it ran first, but still, my debugger hit inside of `ember-code-snippet`'s `included` hook first.

The `before` and `after` directives apply to addons with the same parent as us, but `ember-code-snippet` is actually our child rather that our sibling, so its `included` hook will always be invoked (along any other addons we depend on) when we call `_super` in our own `included` hook.

It looks like `ember-code-snippet` only actually works the way we're using it here at all because it always [reads options from the root application via `findHost`](https://github.com/ef4/ember-code-snippet/blob/1787ab514cf0e18ecd1e2778daa97cb628b8df89/index.js#L14), regardless of whether it's actually a dependency of that app or not.

Given that, I guess setting our host's default options on its behalf needs to happen before we call `_super` in `included`. As long as the host doesn't _also_ include `ember-code-snippet` as a dependency itself, we can safely assume that it won't read its options before then. (And if the host does include it, then... I'm not even sure what will happen with two instance of that addon floating around ¯\\\_(ツ)_/¯)

**Comment by samselikoff** [comment]
I [basically ended up doing that](https://github.com/ember-learn/ember-cli-addon-docs/commit/a00a28e33acea463d82c64fa0a712913d70de3f1#diff-168726dbe96b3ce427e7fedce31bb0bcR84) but it's good to know why. Thanks for taking the time to explain!
