### ISSUE TITLE
Don't run ember deploy on PR CI builds

### ISSUE THREAD

**Issue by samselikoff** [ember-learn/ember-cli-addon-docs#41]

**Comment by dfreeman** [comment]
In the dogfood deploy in this repo, we should only be deploying for builds on `master`: https://github.com/ember-learn/ember-cli-addon-docs/blob/master/config/addon-docs.js#L11

Unfortunately it's tricky to do this in a CI-independent way, because you're operating on specific commit rather than the head of a branch (so `git-repo-info` can't provide a branch name). 

Regardless, it might be less surprising to readers to leave the `shouldDeploy` hook as an escape hatch and include something like this in `travis.yml` instead:

```sh
if [[ $TRAVIS_BRANCH == master && $EMBER_TRY_SCENARIO == ember-default ]]; then
  node_modules/.bin/ember deploy production
fi
```

**Comment by dfreeman** [comment]
This is fixed now
