### ISSUE TITLE
Build failure with scoped package addon

### ISSUE THREAD

**Issue by mriska** [ember-learn/ember-cli-addon-docs#46]
Hi, I was trying out this addon in one of our internal addons. Our addon is hosted privately in an organization scope on npmjs and the `name` in `package.json` is in the form `@organization/package-name`.

When running `ember serve` I got the following error message: 

```shell
› ember s
Livereload server on http://localhost:7020
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
Error: ENOENT: no such file or directory, open '/Users/xxx/work/package-name/tmp/docs_generator-output_path-Krhjlfrc.tmp/docs/project-versions/@organization/package-name-0.5.1+344612b9.json'
  at Object.fs.openSync (fs.js:646:18)
  at Object.fs.writeFileSync (fs.js:1291:33)
  at Object.writeFileSync (/Users/xxx/work/package-name/node_modules/ember-cli-addon-docs/node_modules/jsonfile/index.js:117:13)
  at DocsGenerator.build (/Users/xxx/work/package-name/node_modules/ember-cli-addon-docs/lib/broccoli/docs-generator.js:39:8)
```

And when checking the build output folder `docs_generator-output_path-Krhjlfrc.tmp/docs` I could see that the folders `project-versions` and `projects` were empty. 

When temporary removing the scope from the package name in `package.json` the project builds as expected. 

Should the folder name maybe be taken from the `name` specified in `index.js` instead?

**Comment by dfreeman** [comment]
@mriska I have some code sitting on a local branch called `i-had-these-pending-changes-but-im-not-sure-what-they-were-doing` and seeing this issue reminded me that _that's_ what that code was for! I need to make sure it's actually complete, but I've definitely run into this issue as well and will hopefully have it fixed soon.

I agree that we should treat the name in `index.js` as the definitive source of truth, since that's how Ember CLI sees it, and that's where the base path for module imports comes from as well.

**Comment by mriska** [comment]
Great, I actually started something similar myself to test it out, but didn't want to turn it into a PR before I have heard from you that you think it is actually the right approach.

**Comment by mriska** [comment]
@dfreeman Do you want me to help out with fixing this one or do you have a fix that is close to finished?

**Comment by dfreeman** [comment]
@mriska Sorry about that! There's been a ton of churn in the doc generation code as we moved toward 0.2.0, so the work I originally started on for this no longer applies. If you have the chance to take a look at solving this, a PR would be welcome; otherwise now that things are settled a bit I should be able to come back to it sometime in the next week or two.

One other point of note: as of 3.0, ember-cli issues a warning when your `index.js` name doesn't match your `package.json` name — ideally we should do the right thing whether they match or not (and the addon-docs build still fails for scoped names even when they match), but if it simplifies the fix to be able to assume that the two names are the same, that seems like an ok assumption to start making moving forward.
