### ISSUE TITLE
Images don't resolve correctly in Github hosted documents

### ISSUE THREAD

**Issue by nightire** [ember-learn/ember-cli-addon-docs#74]
<img width="1314" alt="ember_cli_addon_docs" src="https://user-images.githubusercontent.com/1104018/37150996-cb9e8374-230e-11e8-9c59-8dd8eca913b2.png">

Not 100% sure, but I believe Github hosted ember app should change `rootURL` accordingly here: https://github.com/ember-learn/ember-cli-addon-docs/blob/master/tests/dummy/config/environment.js#L8

**Comment by dfreeman** [comment]
We currently set a custom `rootURL` [here](https://github.com/ember-learn/ember-cli-addon-docs/blob/master/tests/dummy/config/environment.js#L53) because the same build can end up deployed to multiple locations with addon-docs.

We may need to introduce a helper, so that snippet would become something like `src={{addon-docs-asset "/assets/images/rick-astley.jpg"}}`

**Comment by ef4** [comment]
This is a general problem for all Ember apps. It's just easy not to notice if you never customize rootURL.

Instead of an `addon-docs-asset` helper, we should just make a standalone addon with a helper named like `<img src={{root-url "assets/images/rick-astley.jpg"}} />`.

**Comment by samselikoff** [comment]
Yep, we've done `{{img-url}}` before and it would be nice for us to provide something like this
