### ISSUE TITLE
Can we make this addon capable of reading the README.md?

### ISSUE THREAD

**Issue by elwayman02** [ember-learn/ember-cli-addon-docs#85]
It would be really nice if there was default support for using README.md from the root project directory in the dummy app, even if the solution was something hacky like copying the .md file into the dummy app at build time. There are a few reasons for this:

1) Addon authors adopting ec-addon-docs will have already written their documentation in README
2) Splitting up their documentation across several pages takes additional time investment to get up and running on this addon.
3) Keeping both the README and the separate "docs" files up-to-date as an addon changes will become a chore
4) If you *don't* have a README, you end up with the result that this addon has, where there is literally no documentation in the repo itself that is easily visible. This problem is compounded by the fact that sites like EmberObserver import your README file when they list your addon.

As a bonus, it would be even more awesome if, instead of requiring separate .md files for each docs route, we could match the route name to a header in README and display everything between that header and the next header that matches a route. This would thereby solve the problem of having nicely organized routes in your documentation app while still having a single readable documentation file for people who are consuming your docs directly from the project page.

**Comment by elwayman02** [comment]
This almost makes me feel like we should ultimately push toward using the Github standard of a `docs/` directory for our markdown files.

**Comment by samselikoff** [comment]
I think we want to start with an Ember app because we know it's flexible enough for sites like Ember concurrency, Liquid fire, etc. For now the best place for that is the dummy app (though we've been talking about an app in `/docs`).

Regarding the README, my thinking is once you have a docs site, you don't want to duplicate docs in README.md. However, I agree there needs to be an extremely easy migration path for addons with a `README.md` file to a docs site. Perhaps if no `index.hbs` or `index.md` file is found, we use `README.md` and throw that into a simple one-page layout. This has the benefit that users will still get versioned docs for their addons.

**Comment by pzuraq** [comment]
Yeah, generally once an addon has a solid docs site the best pattern tends to be just linking directly to the site in the README imo. In my experience, having the README have duplicated information leads to users going directly there, and then asking questions which are answered on the docs site (because they assume the README is the total sum of the documentation).

**Comment by samselikoff** [comment]
Going to close this for now as it's not immediately actionable
