### ISSUE TITLE
Issues with nested components with similar names

### ISSUE THREAD

**Issue by alexlafroscia** [ember-learn/ember-cli-addon-docs#94]
I have a set of two components, `step-manager` and `step-manager/step` (which is `yield`-ed by the manager). I'm running into a number of issues with this scenario

- [ ] I can't generate a documentation page for the `step-manager/step` component because I get an error about the name already being used

<img width="879" alt="screen shot 2018-03-13 at 2 42 01 pm" src="https://user-images.githubusercontent.com/1645881/37371483-b92e9262-26cc-11e8-9231-100cbecc3036.png">

- [ ] The properties on the `step-manager/step` component appear on the `step-manager` page when turning documentation for `step-manager/step` off

**Comment by pzuraq** [comment]
Are you using YUIDoc or ESDoc? What does your documentation look like? Trying to figure out if this is just an app problem or if it's also a build time problem

**Comment by alexlafroscia** [comment]
I pushed my WIP documentation branch here:

https://github.com/alexlafroscia/ember-steps/tree/87a69c5e516eae115f6f48396e4a167bb4eef8c8/addon/components

The `step-manager.js` and `step-component/step.js` are the files in question

**Comment by alexlafroscia** [comment]
It's possible that I accidentally used ESDoc when I should have used YUIDoc... I didn't even realize that was "a thing" that I needed to think about.  The documentation that I'm trying to generate pages for was written a long time ago

**Comment by pzuraq** [comment]
Ah, so you are using YUIDoc (it's the default that gets installed, you can see it in `package.json`). It looks like this issue is that you haven't properly labelled the `step-manager/step.js` component as a class. YUIDoc is very dumb, it does not parse your code at all, so you must tag basically everything. ESDoc is much more intelligent about this, but can only be used with native classes.

**Comment by pzuraq** [comment]
You can read more about how to use the YUIDoc plugin on it's [README](https://github.com/ember-learn/ember-cli-addon-docs-yuidoc#usage), we're working on adding examples to the Sandbox so people can use those as "guides" 😄

**Comment by alexlafroscia** [comment]
Right, so... If I _do_ annotate `step-manager/step.js` as a class, I end up getting an error from the Ember router (see the screenshot in the description of the issue).

**Comment by pzuraq** [comment]
Ok, cool, so two separate issues.

We can probably solve the second issue by throwing at the build step if a class is not annotated. The first problem is definitely an issue with the way the router is set up, we haven't worked on nested components yet because they're non-standard and generally not recommended (very aware that we're using them heavily) and we just haven't had time, been a little overwhelmed 😅

**Comment by alexlafroscia** [comment]
Yeah, totally! Would you be interested in a PR that allows for documenting nested components correctly?

**Comment by pzuraq** [comment]
Absolutely 😄

**Comment by jeff-redshelf** [comment]
I'm having a similar issue with top level components that have similar names (something like x-thing and x-thing-advanced). It looks like the issue is related to matching component paths with module ids.  I'd be happy to open a pull request but I'm not sure if you have rules on contributing to the project.

**Comment by pzuraq** [comment]
Just realized my last comment wasn't clear, I definitely think we should work to support nested components, like it or not they are a pretty commonly used thing and will likely continue to be until Module Unification takes over.

@jeff-redshelf I agree that the logic with matching based on the route is the issue here, it'll iterate through modules as is and find the first one that matches. We can probably update that to either encode more specific information in the navigation index itself, or to run better matching heuristics.

**Comment by jeff-redshelf** [comment]
It might be enough to simply append a / to the end of the path string.
/components/x-thing/ would never match /components/x-thing-advanced

**Comment by mkay581** [comment]
Just ran into this same issue, but my issue is not due to the two nested components, but rather component name prefixes. I have `my-button` and `my-button-list` and it is matching both of them and giving me the same error.
